### ISSUE TITLE
Issue while upgrading from old version

### ISSUE THREAD

**Issue by benutzer-prog** [cnw-co/moodle-local_cnw_smartcohort#10]
I can't upgrade the old version to the new one. 

I only get the error code "Error code: ddlunknownerror".  Maybe there is something wrong with the tables in the upgrade.xml that is different?

After recovery of the old version and the next try to update it runs. But if I want to create a new rule I get these errors:
![image](https://github.com/cnw-co/moodle-local_cnw_smartcohort/assets/55136823/8f1943f1-1ccf-46c9-8c3c-dfbe586140bc)

Best regards
Ben

**Comment by cnw-co** [comment]
Hello Ben,

Sorry about this issue. It occured because of the insufficient number of checks in the upgrade steps (that was fixed in v2.0.5).

In the new version some tables were renamed to make more sense (**cnw_sc_filters** to **cnw_sc_rule** and **cnw_sc_rules** to **cnw_sc_filter**).

Because of the error during your update, the names and properties of the tables did not change properly. That is why the "cnw_sc_rule" table does not exist.

Please try the upgrade with the v2.0.5.

**Comment by benutzer-prog** [comment]
Thank you very much. I tested it. Works perfectly!
